---
name: Infracost
on:
  push:
    paths:
    - '**.tf'
    - '**.tfvars'
    branches: [ master ]
  pull_request:
    paths:
      - '**.tf'
      - '**.tfvars'
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Infracost
        uses: infracost/infracost-gh-action@v0.2.1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          ##### You should only need to modify the following #####
          terraform_dir: ./infrastructure/
    